


BiocManager::install('clusterProfiler')
library(clusterProfiler)

# generated by co-pilot AI
run_GO_enrichment <- function(genes_of_interest, background_genes) {
    # Perform GO enrichment analysis
    go_result <- enrichGO(gene          = background_genes[1:25],
                                                OrgDb         = org.Mm.eg.db, # org.Hs.eg.db,
                                                keyType       = "SYMBOL",
                                                ont           = "BP",
                                                pvalueCutoff  = 0.05,
                                                qvalueCutoff  = 0.05,
                                                readable      = F,
                                                universe      = background_genes)
    
    # Return the enriched GO terms
    return(go_result)
}


# Define the function for GO enrichment analysis using GSEABase package
run_GO_enrichment_GSEABase <- function(genes_of_interest, background_genes) {
    # Load required packages
    library(GSEABase)
    
    # Create the gene set collection
    gene_set_collection <- GeneSetCollection(geneIds = background_genes)
    
    # Create the gene set
    gene_set <- GeneSet(geneIds = genes_of_interest)
    
    # Add the gene set to the collection
    gene_set_collection <- addGeneSet(gene_set_collection, gene_set)
    
    # Perform the enrichment analysis
    enrichment_result <- enricher(gene_set_collection, universe = background_genes)
    
    # Return the enriched GO terms
    return(enrichment_result)
}

# Example usage
background_genes = shorthand_splitnames_v2( rownames(data_container$groups$flib30$dt$rdata) )
genes_of_interest = c('Nppa','Nppb')

go_enrichment_result_GSEABase <- run_GO_enrichment_GSEABase(genes_of_interest, background_genes)
print(go_enrichment_result_GSEABase)





