#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 10 15:19:07 2020

@author: m.wehrens
"""

mystr='GGGAGAGGACTCCTGCACAGTACAGTGGGAGCCGCCTGCCTACGATGGCGGGCAGCCCATCCTGG'
mystr[::-1]

mystr2 = 'GCTACATCCTGGAGCGCAAGAAGAAGAAG'
mystr2[::-1]

'TGGGAGCCGCCTGCCT'[::-1]

''.join(map(str,['-' for i in range(45+14)]))

base_str = 'GCCGGTAATACGACTCACTATAGGGAGTTCTACAGTCCGACGATC'
len(base_str)

bcumilen=8+6
targ_prim_seq = 'GGCTCCAAGTGGCTTTTTTTTTTTTTTTTTTTTTTTTTTTATTTTTAAAAAAAAAATTTTTTTTAAAAATTTGAA'
    # expected barcode is AAGTGGCT
targ_prim_seq[bcumilen:bcumilen+24]
list(range(bcumilen-1,bcumilen+24-1))

targ_prim_seq='TTTTTTTTTTTTTTTTTTTTTTTT'
len(targ_prim_seq)